CREATE DATABASE IF NOT EXISTS user_session_db;
USE user_session_db;

CREATE USER IF NOT EXISTS 'finet_app'@'%' IDENTIFIED BY 'finet_password';
GRANT ALL PRIVILEGES ON user_session_db.* TO 'finet_app'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
    sessions_id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    user_id INT,
    expires_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
